import type { Metadata } from "next";

import "./globals.css";
import NavBarLanding from "@/components/nav-bar-landing/NavBarLanding"




export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
         <NavBarLanding/> 

        {children}
      </body>
    </html>
  );
}
